### PR TITLE
README: Add Nxt Games modules

### PR DESCRIPTION
**Pull request by thetestgame**
Added the open source modules created at Nxt Games for the Panda3D game engine

### CODE REVIEW

**Comment by Moguri** [comment]
I believe these will eventually make a nice addition to the list. However, I would prefer to see a few things first:
* A release that makes it easy to get the module (e.g., a wheel on PyPI)
* The Travis badges not reporting an error

More docs would be nice, but I see that there are least examples, which is good.

**Comment by thetestgame** [comment]
I can work on the PyPi releases. Travis might be more of an issue. That was not my doing originally. I'm not familiar with Travis enough to setup the environments and dependencies for that.

**Comment by Moguri** [comment]
Then I would recommend taking the badge out of the readme.

**Comment by thetestgame** [comment]
I took them out. I also starting prepping the modules for PyPi. However, I don't know if there is a clean way to do p3d-discord. From what I've learned before interrogate modules are picky about where they are placed on Mac OS. I don't know as though the standard site packages install will run on a Mac.

**Pull request closed without merging**
